host = "[::]:8080"
pub_dir = "public"
##db_protocol = "mysql://root:root@localhost/database"
##db_protocol = "sqlite://database.db"
route_root = ""
secret_key = "123456789"
assets_listing = true
[log]
dir = "./log"
prefix = "webserver.log"
utcoffset = [8, 0, 0]
level = "debug" # debug, info, error, warn, trace

[http3]
dir = "./cert/"
cert_file_name = "cert.pem"
key_file_name = "key.pem"

# [[database]]
# name = "db_1"
# protocol = "mysql://root:root@localhost/database"
